<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-22T05:49:47Z" name="Default suite" finished-at="2023-03-22T05:50:18Z" duration-ms="30514">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleEventWrapper, io.cucumber.testng.CucumberFeatureWrapper)[pri:0, instance:com.runner.TestRunner@67545b57]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2023-03-22T05:49:47Z" name="Default test" finished-at="2023-03-22T05:50:18Z" duration-ms="30514">
      <class name="com.runner.TestRunner">
        <test-method is-config="true" signature="setUpClass()[pri:0, instance:com.runner.TestRunner@67545b57]" started-at="2023-03-22T05:49:47Z" name="setUpClass" finished-at="2023-03-22T05:49:48Z" duration-ms="254" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleEventWrapper, io.cucumber.testng.CucumberFeatureWrapper)[pri:0, instance:com.runner.TestRunner@67545b57]" started-at="2023-03-22T05:49:48Z" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-03-22T05:50:04Z" duration-ms="16099" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Login page with invalid Credentials"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Facebook page validation"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.steps.StepDefinition.user_verify_the_error_message(StepDefinition.java:54)
at ✽.User verify the error message(file:src/test/resources/features/loginpage.feature:12)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleEventWrapper, io.cucumber.testng.CucumberFeatureWrapper)[pri:0, instance:com.runner.TestRunner@67545b57]" started-at="2023-03-22T05:50:04Z" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-03-22T05:50:18Z" duration-ms="14029" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Login page with invalid Credentials"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Facebook page validation"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.steps.StepDefinition.user_verify_the_error_message(StepDefinition.java:54)
at ✽.User verify the error message(file:src/test/resources/features/loginpage.feature:12)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:com.runner.TestRunner@67545b57]" started-at="2023-03-22T05:50:18Z" name="tearDownClass" finished-at="2023-03-22T05:50:18Z" duration-ms="51" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.runner.TestRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
